# Numpy 

Images are 3D in numpy array

In [1]:
# importing numpy package
import numpy as np

### Limitation of List: 

In [2]:
list1 = [1,2,3,4,5]
print(list1*5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [3]:
list1 = [1,2,3,4,5]
print(list1 + 5)

TypeError: can only concatenate list (not "int") to list

In [4]:
list1 = [1,2,3,4,5]
list2 = [1,2,3,4,5]
print(list1 + list2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## Introduction of Numpy Arrays

In [17]:
l1 = [1,20,-300,4,5]
a = np.array(l1)

print("Datatype of Array: ",type(a))  # print type of array
print("Size: ",a.size)   # print size
print("Dimension: ",a.ndim)   # print dimension 
print("Shape: ",a.shape)  # print shape of array

print("np.array: ",a)

print("Sum: ",np.sum(a)) # print sum of array
print("Max: ",np.max(a)) # print max of array 
print("Min: ",np.min(a)) # print min of array 
print("Index of Max: ",np.argmax(a)) # print index of max 
print("Index of Min: ",np.argmin(a)) # print index of min
print("Mean: " , np.mean(a)) # print mean

Datatype of Array:  <class 'numpy.ndarray'>
Size:  5
Dimension:  1
Shape:  (5,)
np.array:  [   1   20 -300    4    5]
Sum:  -270
Max:  20
Min:  -300
Index of Max:  1
Index of Min:  2
Mean:  -54.0


In [18]:
# append
a = np.append(a,230)
print(a)

[   1   20 -300    4    5  230]


In [19]:
# insertion
a = np.insert(a,2,-1100)
print(a)

[    1    20 -1100  -300     4     5   230]


In [20]:
# multiplying n 
print(a*5)

[    5   100 -5500 -1500    20    25  1150]


In [21]:
# adding n 
print(a+500)

[ 501  520 -600  200  504  505  730]


In [22]:
# power of array
print(a ** 2)

[      1     400 1210000   90000      16      25   52900]


In [24]:
# performing maths on arrays
A = np.array([1,2,3,4])
B = np.array([1,2,3,4])
print(A+B)
print(A*B)
print(A-B)
print(A/B)

[2 4 6 8]
[ 1  4  9 16]
[0 0 0 0]
[1. 1. 1. 1.]


In [25]:
A1 = np.array([
    [1,2,3],
    [4,500,6],
    [7,-800,9]
])

print("Datatype of Array: ",type(A1))  # print type of array
print("Size: ",A1.size)   # print size
print("Dimension: ",A1.ndim)   # print dimension 
print("Shape: ",A1.shape)  # print shape of array

print("np.array: ",A1)

print("Sum: ",np.sum(A1)) # print sum of array
print("Max: ",np.max(A1)) # print max of array 
print("Min: ",np.min(A1)) # print min of array 
print("Index of Max: ",np.argmax(A1)) # print index of max 
print("Index of Min: ",np.argmin(A1)) # print index of min
print("Mean: " , np.mean(A1))

Datatype of Array:  <class 'numpy.ndarray'>
Size:  9
Dimension:  2
Shape:  (3, 3)
np.array:  [[   1    2    3]
 [   4  500    6]
 [   7 -800    9]]
Sum:  -268
Max:  500
Min:  -800
Index of Max:  4
Index of Min:  7
Mean:  -29.77777777777778


In [26]:
# indentity matrix
A = np.identity(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
A = np.identity(10)
print(A)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [35]:
# only ones matrix
A = np.ones(10)
print(A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [29]:
# only zero matrix
A = np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
A = np.zeros((3,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
A = np.zeros(((2,5,5)))
print(A)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [37]:
A = np.ones((((1,12,4,7))))
print(A)

[[[[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1

In [40]:
# any particular value filling
A = np.full(((2,3,4)),5000)
print(A)

[[[5000 5000 5000 5000]
  [5000 5000 5000 5000]
  [5000 5000 5000 5000]]

 [[5000 5000 5000 5000]
  [5000 5000 5000 5000]
  [5000 5000 5000 5000]]]


In [41]:
# use of random
A = np.random.random(5)
print(A)

[0.36769998 0.02333404 0.74043641 0.89100863 0.97127602]


In [42]:
A = np.random.random((3,3))
print(A)

[[0.52636358 0.55057035 0.12046681]
 [0.89125861 0.08200059 0.35774573]
 [0.7271952  0.82444079 0.88871389]]


In [43]:
A = np.random.random(((2,3,3)))
print(A)

[[[0.66687487 0.0208491  0.32587351]
  [0.66102727 0.45822792 0.8291409 ]
  [0.95263407 0.65117876 0.91722249]]

 [[0.31513949 0.66232645 0.31166095]
  [0.49154689 0.68092198 0.86168286]
  [0.05360142 0.24989213 0.34570035]]]


In [44]:
# use of randint 
A = np.random.randint(1,10, 5)
print(A)

[6 9 1 5 6]


In [45]:
A = np.random.randint(1,10, (3,3))
print(A)

[[4 7 7]
 [5 3 2]
 [4 6 8]]


In [56]:
A = np.random.randint(1,5, (3,3))
B= np.random.randint(1,5, (3,3))
print(A)
print()  # it is just for line break
print(B)

[[3 2 4]
 [1 2 1]
 [3 3 3]]

[[3 2 2]
 [1 4 3]
 [3 1 3]]


In [57]:
print("Addition: \n",A+B)
print("Subtraction: \n",A-B)
print("Addition: \n",A*B)
print("Division: \n",A/B)

Addition: 
 [[6 4 6]
 [2 6 4]
 [6 4 6]]
Subtraction: 
 [[ 0  0  2]
 [ 0 -2 -2]
 [ 0  2  0]]
Addition: 
 [[9 4 8]
 [1 8 3]
 [9 3 9]]
Division: 
 [[1.         1.         2.        ]
 [1.         0.5        0.33333333]
 [1.         3.         1.        ]]


In [59]:
# dot product:
print(A@B)
print(A.dot(B))

[[23 18 24]
 [ 8 11 11]
 [21 21 24]]
[[23 18 24]
 [ 8 11 11]
 [21 21 24]]


In [61]:
# Example of Images array 
A = np.random.randint(0,255,((3,5,5)))
print(A)

[[[ 80  93  63 199 108]
  [ 65  11 127  85 191]
  [197 181  14 194 179]
  [ 40 180 135 117  11]
  [197 218 108  30 145]]

 [[ 28 216  83  16 178]
  [ 93  60 222 144  91]
  [181  88 238  88 194]
  [119  51 106 120 252]
  [252   9  58 253  31]]

 [[ 76  19 104 109 244]
  [  7  21 192 140 134]
  [253  62  49 100  85]
  [ 29 118 215  90 125]
  [176 151 243  43  97]]]


In [71]:
# printing the even number of array 
B = np.array([])

print("Even Array:")
for a in A:
    for b in a:
        for c in b:
            if c%2 == 0:
                print(c,end=", ")
                B = np.append(B,c)

Even Array:
80, 108, 14, 194, 40, 180, 218, 108, 30, 28, 216, 16, 178, 60, 222, 144, 88, 238, 88, 194, 106, 120, 252, 252, 58, 76, 104, 244, 192, 140, 134, 62, 100, 118, 90, 176, 

In [74]:
print("Even Array: \n" ,B)
print("Size of Even Array: \n" ,B.size)

Even Array: 
 [ 80. 108.  14. 194.  40. 180. 218. 108.  30.  28. 216.  16. 178.  60.
 222. 144.  88. 238.  88. 194. 106. 120. 252. 252.  58.  76. 104. 244.
 192. 140. 134.  62. 100. 118.  90. 176.]
Size of Even Array: 
 36


In [76]:
# This will filter us the even number of array A
print(A[A%2==0])

[ 80 108  14 194  40 180 218 108  30  28 216  16 178  60 222 144  88 238
  88 194 106 120 252 252  58  76 104 244 192 140 134  62 100 118  90 176]


In [80]:
# use of np.arange
A = np.arange(10)
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [82]:
# use of reshape method
print(A.reshape(1,10))

[[0 1 2 3 4 5 6 7 8 9]]


In [84]:
print(A.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [85]:
print(A.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [87]:
A = np.arange(12)
print(A.reshape(2,2,3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [2]:
A = np.random.randint(0,255,((3,5,5)))
print(A)
print(type(A))

[[[118 213 214 117  61]
  [ 73  10  36 238 106]
  [199  75 137 233 174]
  [127 181  19   6 109]
  [ 31 166 163 145 176]]

 [[  0 165 232 127  31]
  [158 232 209 207  91]
  [251  97   8 230  18]
  [217  43  52 184 100]
  [ 68  89  50  92  63]]

 [[204  34   4  30   5]
  [ 28  98 125 127 114]
  [237 246 224 167 157]
  [ 48  72  51  55  31]
  [ 98 251 148 123 237]]]
<class 'numpy.ndarray'>


### Inline Filtering without using loops

In [4]:
# printing evern numbers
print(A[A%2 == 0])

[118 214  10  36 238 106 174   6 166 176   0 232 158 232   8 230  18  52
 184 100  68  50  92 204  34   4  30  28  98 114 246 224  48  72  98 148]


In [6]:
# print numbers which are even and also divisible on 10 
print(A[(A%2 == 0) & (A%10 == 0)])

[ 10   0 230 100  50  30]


In [7]:
# print numbers which are even and divisible on 7 or 3
print(A[(A%2 == 0) & ((A%7 == 0) | (A%3 == 0))])

[ 36 238 174   6   0  18 204  30  28  98 114 246 224  48  72  98]
