# <center><b>ML ASSIGNMENT 5</b></center>

## Import numpy as given example import numpy as your first name

In [45]:
import numpy as hamid

## <b>Q1: Must follow following steps:</b>
### Develop two 1-D integer arrays named A and B.
### The size of each array should be equal to the last four digits of your AG number.
### For example, if the last four digits are 5010, then the array size will be 5010.
### Let the last four digits of your AG number be 5010.
### Then the starting point is –5010 and the ending point is 5010.

In [46]:
A = hamid.random.randint(-7206,7206,7206)
B = hamid.random.randint(-7206,7206,7206)
print(A)
print(B)

[ 6623   577 -2709 ...  1076  4762 -4792]
[  -14  5289  6140 ...  -789  6085 -7128]


### Perform the following operations:
> #### <b>Find the sum of the two arrays.</b>

In [47]:
print('Sum: ',A+B)

Sum:  [  6609   5866   3431 ...    287  10847 -11920]


> #### <b>Find the difference of the two arrays.</b>

In [48]:
print('Diffrence: ', A-B)

Diffrence:  [ 6637 -4712 -8849 ...  1865 -1323  2336]


> #### <b>Find the element-wise multiplication of the two arrays.</b>

In [49]:
print('Multiplication: ',A*B)

Multiplication:  [   -92722   3051753 -16633260 ...   -848964  28976770  34157376]


> #### <b>Divide one array by the other (element-wise division).</b>

In [50]:
print('Division: ',A/B)

Division:  [-4.73071429e+02  1.09094347e-01 -4.41205212e-01 ... -1.36375158e+00
  7.82580115e-01  6.72278339e-01]


/tmp/ipython-input-739205791.py:1: RuntimeWarning: divide by zero encountered in divide
  print('Division: ',A/B)


> #### <b>Find the cube (power of 3) of the first array.</b>

In [51]:
print('A^3: ',pow(A,3))

A^3:  [ 290512126367     192100033  -19880486829 ...    1245766976  107986178728
 -110039961088]


> #### <b>Find the maximum value in array A.</b>

In [52]:
print('Maximum: ',hamid.max(A))

Maximum:  7204


> #### <b>Find the minimum value in array B.</b>

In [53]:
print('Minimum: ',hamid.min(B))

Minimum:  -7205


> #### <b>Find the index positions containing the maximum and minimum values.</b>

In [54]:
print('Index of Max: ',hamid.argmax(A))
print('Index of Min: ',hamid.argmin(B))

Index of Max:  2342
Index of Min:  6732


## <b>Q2: Must follow following steps:</b>

### Develop 2-D integer arrays named A.
### For example, if the last four digits are 5010, then the array size will be 50×10 OR if the last four digits are 5000, then the array size will be 50×50
### Let the last four digits of your AG number be 5010.
### Then the starting point is –5010 and the ending point is 5010.



In [55]:
A = hamid.random.randint(-7206,7206,(72,6))
print(A)

[[ 4221 -2472  4863 -5787  6081  3604]
 [  553  6963  3078  -873  3535 -5494]
 [ 1586 -2036  -810  3835  1871 -4992]
 [-3876  6171 -3180  -526 -6710  3862]
 [-6237  2582  4144  -314  1554 -6260]
 [ 6370  5829 -2299  4810 -3342 -5316]
 [-1758 -3089  3008 -5713 -5203 -3856]
 [-3445 -2876 -3030 -5154 -6277  2282]
 [-1859  1661 -5456  7112  1558  5563]
 [ 1779  2648  5956  6013  3267 -4510]
 [ 1546 -6589  2542 -7063 -1215  6558]
 [ 1068  3206 -1657  6805  4674  2738]
 [ 6748  2244  -202  1027 -6619 -2708]
 [ -622   127  7095  -102     2  4109]
 [ 6851 -5942 -1006  4286 -4092 -1825]
 [ 2009  -529   767 -5921  6732 -1314]
 [ 6772  3127  6542  -569  2901 -3460]
 [ -811  1970  2627 -1932  2413  2785]
 [ 1145   153 -2432  3691  4587  2445]
 [ 4749 -4537  3503 -2830 -1104  4905]
 [ 6266 -3824 -3581 -1911  1206 -4178]
 [-4467 -6913 -1777 -4722 -3225  3214]
 [  745  -530 -2612 -2742 -1625  3217]
 [ 1506 -3298 -3463  2889 -6421  3231]
 [  447   508 -4198  3183 -4600 -3950]
 [  394 -5562 -5596  4269

### Perform the following operations:
> #### <b>Print Positive Even</b>

In [56]:
print(A[(A > 0) & (A % 2 == 0)])

[3604 3078 1586 3862 2582 4144 1554 6370 4810 3008 2282 7112 1558 2648
 5956 1546 2542 6558 1068 3206 4674 2738 6748 2244    2 4286 6732 6772
 6542 1970 6266 1206 3214 1506  508  394  908 2256    8 4262 7128 2560
 6304 1466 2828 3890 4490 6252 5222 4266  476 3154 2546  310 3234 5992
 1382 4102 1914 1412 1422 3798 6622 3100 4368 6998 5894 4622  604 5276
 3264 4330 1280 6710 6914 5062 2218 6614 3104 6290  780 6038 5640  690
 2930 2178   68 1354 2282  352 3700 2268 5476 5982 6390 3996 5710 3890
  702   92 3468 2544 6108 3138 6250 1026]


> #### <b>Print negative even</b>

In [57]:
print(A[(A < 0) & (A % 2 == 0)])

[-2472 -5494 -2036  -810 -4992 -3876 -3180  -526 -6710  -314 -6260 -3342
 -5316 -1758 -3856 -2876 -3030 -5154 -5456 -4510  -202 -2708  -622  -102
 -5942 -1006 -4092 -1314 -3460 -1932 -2432 -2830 -1104 -3824 -4178 -4722
  -530 -2612 -2742 -3298 -4198 -4600 -3950 -5562 -5596 -1082 -6132 -5678
 -2126 -1606 -5288 -3674  -758 -4458 -1572  -674 -3688 -5240 -7074 -1460
   -70 -5844 -6504 -3436 -2414 -5656 -4922 -6596 -3512 -4524 -1920 -2982
 -6430 -5192 -2878 -5230 -5266 -6852 -4990 -6366 -1034 -2344 -3246 -2090
 -6460 -3740 -6292 -3090  -978 -1098 -5262 -4744 -3592  -934 -2730 -1800
 -5782 -4520 -2790 -2130 -5170 -6598 -2644 -1122 -3626 -2408 -4720 -6002
 -4742 -5790  -366 -6220 -2506 -2500 -2846 -3148]


> #### <b>Print Positive odd</b>

In [58]:
print(A[(A > 0) & (A % 2 != 0)])

[4221 4863 6081  553 6963 3535 3835 1871 6171 5829 1661 5563 1779 6013
 3267 6805 1027  127 7095 4109 6851 2009  767 3127 2901 2627 2413 2785
 1145  153 3691 4587 2445 4749 3503 4905  745 3217 2889 3231  447 3183
 4269 3071 2017  547 6889 2061   85 4269 3541 2437 4777 3555 5191    3
 2261 7093 1413 1417 3211  295  549 6005 2195 4399 3513 4807  177 6721
 1255 3557 3647 4769 3813 4011 5983 1745 5693 6441 5155 5935 5203 5225
 6709 4725 5497 4447 2589  193 1255 4535 2947  627  435 6651 2273  407
 4803 2987 5615 2813 1961 5901  555 2019 4573 5413 1099 4323 2681  993]


> #### <b>Print negative odd</b>

In [59]:
print(A[(A < 0) & (A % 2 != 0)])

[-5787  -873 -6237 -2299 -3089 -5713 -5203 -3445 -6277 -1859 -6589 -7063
 -1215 -1657 -6619 -1825  -529 -5921  -569  -811 -4537 -3581 -1911 -4467
 -6913 -1777 -3225 -1625 -3463 -6421  -915 -1343 -3605  -369 -4497 -1981
 -6287 -3899 -4659 -6111 -1291 -3743 -1271 -3049 -1981 -5699 -4169 -1635
 -1873 -4909 -1867 -2603 -4655 -3171 -2981 -7175  -485 -3811 -1449 -4203
  -909 -2629 -6691 -5575 -6537 -5541 -4723 -1471 -3939 -3603 -2811 -2865
 -5961 -3887 -4519 -1717 -3215 -3485 -2865 -4081 -1827 -4591 -4343 -5963
 -3995  -357  -117 -4345 -2449  -965 -2247  -323 -4673 -6495  -693 -2583
 -3395 -3413]


> #### <b>Print sum of all elements</b>

In [60]:
print('Sum of Array "A": ',hamid.sum(A))

Sum of Array "A":  5076


> #### <b>Print row wise sum</b>

In [61]:
print('Row wise Sum: \n',hamid.sum(A,axis=1))

Row wise Sum: 
 [ 10510   7762   -546  -4259  -4531   6052 -16611 -18500   8579  15153
  -4221  16834    490  10609  -1728   1744  15313   7052   9589   4686
  -6022 -17890  -3547  -5556  -8610  -6669  10082   5865   6533  17888
  -9608   2781   4757  -2410  12469  -6511  11071  19013 -19882   4791
  13449  -9985  -4076   -928  -6458 -22204   9543  -7701  15085 -18414
  -1865 -10478   9117  11956    -36  -7060  -8981   5145   4694   2815
   1964 -14411 -10030   3185   -976 -16040   2032 -16702   5010   6417
  -5902   4389]


> #### <b>Print column wise sum</b>

In [62]:
print('Column wise Sum: \n',hamid.sum(A,axis=0))

Column wise Sum: 
 [ 19047   -547 -22854   3177  15247  -8994]


> #### <b>Print number may be even or dividable on 10</b>

In [63]:
print(A[(A % 2 == 0) | (A % 10 == 0)])

[-2472  3604  3078 -5494  1586 -2036  -810 -4992 -3876 -3180  -526 -6710
  3862  2582  4144  -314  1554 -6260  6370  4810 -3342 -5316 -1758  3008
 -3856 -2876 -3030 -5154  2282 -5456  7112  1558  2648  5956 -4510  1546
  2542  6558  1068  3206  4674  2738  6748  2244  -202 -2708  -622  -102
     2 -5942 -1006  4286 -4092  6732 -1314  6772  6542 -3460  1970 -1932
 -2432 -2830 -1104  6266 -3824  1206 -4178 -4722  3214  -530 -2612 -2742
  1506 -3298   508 -4198 -4600 -3950   394 -5562 -5596   908 -1082  2256
     8 -6132  4262  7128  2560  6304 -5678  1466 -2126  2828  3890 -1606
  4490 -5288  6252  5222  4266 -3674   476  3154  2546   310  3234  5992
  1382  4102  -758  1914 -4458  1412 -1572  -674  1422  3798  6622  3100
  4368 -3688 -5240  6998 -7074 -1460  5894   -70  4622 -5844   604 -6504
 -3436  5276 -2414  3264 -5656 -4922 -6596 -3512 -4524 -1920  4330 -2982
  1280  6710  6914 -6430  5062  2218  6614 -5192 -2878 -5230 -5266 -6852
 -4990  3104 -6366 -1034 -2344  6290   780 -3246 -2

> #### <b>Print number must be odd, positive and dividable 11</b>

In [64]:
print(A[(A % 2 != 0) & (A > 0) & (A % 11 == 0) ])

[6963 6171 1661 3267 7095 4587 4807 6721 5203 5225  627  407 4323]


> #### <b>Print total number of positive even</b>

In [65]:
print('Size of Positive Even Numbers: ',A[(A > 0) & (A % 2 == 0)].size)

Size of Positive Even Numbers:  106


> #### <b>Print total number of negative even</b>

In [66]:
print('Size of Negitive Even Numbers: ',A[(A < 0) & (A % 2 == 0)].size)

Size of Negitive Even Numbers:  116


> #### <b>Print total number of even</b>

In [67]:
print('Size of Even Numbers: ',A[A % 2 == 0].size)

Size of Even Numbers:  222


> #### <b>Print total number of odd</b>

In [68]:
print('Size of Odd Numbers: ',A[A % 2 != 0].size)

Size of Odd Numbers:  210


## Q3: Must follow following steps:

### Develop 4-D integer arrays named A.
### For example, if the last four digits are 5010, then the array size will be 50×10×10×10 OR if the last four digits are 5000, then the array size will be 50×50×50×50*
### Let the last four digits of your AG number be 5010. Then the starting point is -5010 and the ending point is 5010.

In [69]:
A = hamid.random.randint(-7206,7206,(((72,6,6,6))))
print(A)

[[[[ 4955  4644 -6039  -401  5183  2298]
   [-4903 -1276 -1691  4806  4943  3646]
   [ 5633 -2591  -835 -6160  1513  6976]
   [-1407  2936  1235  6292 -5595  3046]
   [ 1208 -3218 -2907  3863  3089 -2562]
   [-4880 -1944  2007 -3634 -2615 -6589]]

  [[-5775  4804  -241 -4160 -4385  5113]
   [-4522 -7115  -841   493  2245  3765]
   [  817  3472  3268  3341 -6412  1871]
   [ 2759 -2062 -4437  3626  2085 -5504]
   [ 6151 -2273  -748 -1380 -4839 -5367]
   [ 6951 -6592  6239 -1973 -5241 -4208]]

  [[ 3858  1628 -4312  5152  3159 -2869]
   [ 1603 -3734 -6202 -7152  3220 -1874]
   [ 3478  -894 -3528 -4065 -4331  2976]
   [-5890 -1390  3668   559 -6817 -2157]
   [-6282 -5212  -975  6375 -1437 -1214]
   [-4821 -4173 -1614  2398 -3196   750]]

  [[ 3987  1014 -6900  5934   876  4844]
   [ 6075  -686  1120  3530  4232  5023]
   [  517 -4573 -3205  -798 -1243 -2885]
   [ 6773 -5415 -6933  4106 -1026  4295]
   [ 1502 -3210 -1550  -214  2655  1208]
   [-5279 -2490 -7056 -4645  1496 -4711]]

  [[-703

### Perform the following operations:
> #### <b>Print Positive Even</b>

In [70]:
print('Positive Even: ',A[(A > 0) & (A % 2 == 0)])

Positive Even:  [4644 2298 4806 ... 4548 4614 3724]


> #### <b>Print numbers those dividable your first two digits of AG numbers.</b>

In [71]:
print('Divisible on "72": ',A[A % 72 == 0])

Divisible on "72":  [-1944 -3528 -7056 -1584 -2520  6696 -1512    72 -5760 -3744 -4392  3744
 -6336  1296  2880 -3096  2520  1872  1080  4680  4680 -5616  3816 -1368
 -1728  2736 -1368  -144  5400 -4968  -144 -5904 -1728   936   360 -6264
 -1656  4824    72 -1440  6408 -6048  4608  -144  3672  3384 -6264 -3744
  6120  2376  4320  3672 -1944 -5616 -5256  6696 -4104  5976 -3384 -1440
  6768   360 -1008   504 -6336 -2016 -3600  -504 -7056   144 -1080  3888
  3528  1800   792  2088  5472  -648  2088  -792 -4320 -1224 -3528  6120
  5328  2304  1656   216   432 -5112 -4896  6264  5976  4176 -6120 -1512
 -3888 -1512  -432 -4752 -2232   432 -5184 -6624 -4176 -2592  4752  -144
 -2664  -792 -6192 -3528 -5256 -3168 -6120  4536 -5688 -4536 -5040  -432
 -5472  6552   216 -1728  6408 -2088 -1512   360  7200 -5400  6984  6408
  6768 -5112  5112 -1224  6480 -4176  2448 -7056  6120   792 -5976  4104
 -5904  4752 -3456 -1080  5976 -6048 -6480 -3816 -3456  6768  4176  3240
 -1440 -5256  3600 -3312  6480 

> #### <b>Print total number of zeros</b>

In [72]:
print('Total Zeros :',A[A == 0].size)

Total Zeros : 0


> #### <b>Print only negative values</b>

In [73]:
print('Negitive: ',A[A < 0])

Negitive:  [-6039  -401 -4903 ...  -426 -2277 -1060]


> #### <b>Print size of original arrays</b>

In [74]:
print('Size: ',A.size)

Size:  15552


> #### <b>Print negative even</b>

In [75]:
print("Negitive Even: ",A[(A < 0) & (A % 2 ==0)])

Negitive Even:  [-1276 -6160 -3218 ... -4206  -426 -1060]


> #### <b>Print Positive odd</b>

In [76]:
print("Positive Odd: ",A[(A > 0) & (A % 2 !=0)])

Positive Odd:  [4955 5183 4943 ... 2729 4377 6539]


> #### <b>Print negative odd</b>

In [77]:
print("Negitive Odd: ",A[(A < 0) & (A % 2 !=0)])

Negitive Odd:  [-6039  -401 -4903 ... -3187 -3111 -2277]


> #### <b>Print number may be even or dividable on 10</b>

In [78]:
print(A[(A % 2 == 0) | (A % 10 == 0)])

[ 4644  2298 -1276 ... -1060  4614  3724]


> #### <b>Print number must be odd, positive and dividable 11</b>

In [79]:
print(A[(A % 2 != 0) & (A > 0) & (A % 11 == 0)])

[ 517  231 1947 4807  913 2365 5863 3531 6831 1573 1661 7095 6171 1111
 2915 4719 6721 5291 1617 3289 3267 6325   11 3025 2189  539 4851 1001
 5797 1727 3531 6633 5445 2299 3553  803 4279 4851 1573 6655 5445 2805
 4455 6105 1001 1683 1771 7117 3795  429  803 1353 2673 5621  165 1353
 4279 5907 3729 6831  187  429 4565 6765 2739 5555 2321 5137 5577 1155
  363 5687 2123 1419 4169 6699 3509  825 5335 1023 5225  561   77 6655
 4719  121  583 6479 1639   33 2189 4587 4829 2233 6215 6589  429 4565
  869 1419 2805 5137 2453 4873 5819 4147 1639 5929 6941 6611 1793 6347
 2079 6127 6193 2629 1111  385 5907 2145 6325 3003 2783 1441 6325 6545
 3509 3509 6699  979 2739 3597 5841 3289 1001 6721 2233 4741 4345 6391
 6897   33 2145 6963  891 5841 4169 4213 1441 7051 1749 6721  517 6325
 2365 2255 4829 4301 1617 1089 5973 6083 3773 3773 2277 2541 6633 3905
 3135 4983 2541 2387 2343 2717 2761 6039 5555 3883 5005 6853 1221 4081
 5687 3487 1243 3399 6215 4037 3817 6919 3531  187 6039  627 4917 6237
 5643 

> #### <b>Print total number of positive even</b>

In [80]:
print('Size of Positive Even: ',A[(A > 0) & (A % 2 == 0)].size)

Size of Positive Even:  3784


> #### <b>Print total number of negative even</b>

In [81]:
print('Size of Negitive Even: ',A[(A < 0) & (A % 2 == 0)].size)

Size of Negitive Even:  3936


> #### <b>Print total number of even</b>

In [82]:
print('Size of Even: ',A[A % 2 == 0].size)

Size of Even:  7720


> #### <b>Print total number of odd</b>

In [83]:
print('Size of Odd: ',A[A % 2 != 0].size)

Size of Odd:  7832
